#include "farversion.hpp"
//#include "plugin.hpp"

#define PLUGIN_BUILD 9
#define PLUGIN_DESC L"test"
#define PLUGIN_NAME L"SplitFile.dll"
#define PLUGIN_FILENAME L"SplitFile.dll"
#define PLUGIN_AUTHOR FARCOMPANYNAME
#define PLUGIN_VERSION MAKEFARVERSION(FARMANAGERVERSION_MAJOR,FARMANAGERVERSION_MINOR,FARMANAGERVERSION_REVISION,PLUGIN_BUILD,VS_RELEASE)
